sudo: false

language: node_js

node_js:
  - "8.3.0"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - cd hello_world
  - npm install
  - npm run lint
  - npm run test
  - cd client
  - npm run test

branches:
  only:
  - gh-pages
  - /.*/
