sudo: false

language: node_js

node_js:
  - "8.3.0"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - cd hello_world && npm install && npm run lint && npm run test
  - NODE_ENV=development nodemon hello_world/server.js

branches:
  only:
  - gh-pages
  - /.*/
